/*
 *              ______                        ____              __ 
 *             / ____/___ _____ ___  ___     / __ )____  ____  / /_
 *            / / __/ __ `/ __ `__ \/ _ \   / __  / __ \/ __ \/ __/
 *           / /_/ / /_/ / / / / / /  __/  / /_/ / /_/ / /_/ / /_  
 *           \____/\__,_/_/ /_/ /_/\___/  /_____/\____/\____/\__/  
 *                                                 
 *                                 .-'\
 *                              .-'  `/\
 *                           .-'      `/\
 *                           \         `/\
 *                            \         `/\
 *                             \    _-   `/\       _.--.
 *                              \    _-   `/`-..--\     )
 *                               \    _-   `,','  /    ,')
 *                                `-_   -   ` -- ~   ,','
 *                                 `-              ,','
 *                                  \,--.    ____==-~
 *                                   \   \_-~\
 *                                    `_-~_.-'
 *                                     \-~
 * 
 *                       http://mrstampy.github.io/gameboot/
 *
 * Copyright (C) 2015 Burton Alexander
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 * 
 */
package com.github.mrstampy.gameboot.exception;

/**
 * Checked exception generated by GameBoot.
 */
public class GameBootException extends Exception {

  private static final long serialVersionUID = -3167138308922775541L;

  private Object[] payload;

  /**
   * Instantiates a new game boot exception.
   *
   * @param payload
   *          the payload
   */
  public GameBootException(Object... payload) {
    super();
    setPayload(payload);
  }

  /**
   * Instantiates a new game boot exception.
   *
   * @param message
   *          the message
   * @param payload
   *          the payload
   */
  public GameBootException(String message, Object... payload) {
    super(message);
    setPayload(payload);
  }

  /**
   * Instantiates a new game boot exception.
   *
   * @param cause
   *          the cause
   * @param payload
   *          the payload
   */
  public GameBootException(Throwable cause, Object... payload) {
    super(cause);
    setPayload(payload);
  }

  /**
   * Instantiates a new game boot exception.
   *
   * @param message
   *          the message
   * @param cause
   *          the cause
   * @param payload
   *          the payload
   */
  public GameBootException(String message, Throwable cause, Object... payload) {
    super(message, cause);
    setPayload(payload);
  }

  /**
   * Instantiates a new game boot exception.
   *
   * @param message
   *          the message
   * @param cause
   *          the cause
   * @param enableSuppression
   *          the enable suppression
   * @param writableStackTrace
   *          the writable stack trace
   * @param payload
   *          the payload
   */
  public GameBootException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace,
      Object... payload) {
    super(message, cause, enableSuppression, writableStackTrace);
    setPayload(payload);
  }

  /**
   * Checks for payload.
   *
   * @return true, if successful
   */
  public boolean hasPayload() {
    return payload != null && payload.length > 0;
  }

  /**
   * Gets the payload.
   *
   * @return the payload
   */
  public Object[] getPayload() {
    return payload;
  }

  /**
   * Sets the payload.
   *
   * @param payload
   *          the new payload
   */
  public void setPayload(Object[] payload) {
    this.payload = payload;
  }

}
